### ISSUE TITLE
:[range]JupyterSendRange not working

### ISSUE THREAD

**Issue by aydoo** [wmvanvliet/jupyter-vim#13]
When I use :[range]JupyterSendRange I get and error. Example

When I select something in Visual mode and execute :'<,'>JupyterSendRange I get the following error:

`Error detected while processing function jupyter#SendRange:`
`line    1:`
`E481: No range allowed: 8,9Pythonx juypter_vim.send_range()`

Using the latest version of jupyter-vim and vim 8+.

**Comment by mmyrte** [comment]
I, too, have this problem. Since I am not at all versed in vimscript, I would be glad for some pointers on how to help debugging this.

I'm using neovim 0.3.4 and the latest commit of jupyter-vim (66d9935f13060edc3fda1020d0431f1bf40ca991).
