### ISSUE TITLE
Wrap file name in double quotes on Windows

### ISSUE THREAD

**Issue by DaanJG** [wmvanvliet/jupyter-vim#17]
Hi,

Thanks for your work on jupyter-vim.

On Windows, I get an error in the Jupyter console when doing `:JupyterRunFile`:

```
[remote] In [1]: %run  'C:\\Users\\Daan\\.jupyter\\jupyter_console_config.py'
c:\users\d16342\appdata\local\programs\python\python37\lib\site-packages\IPython\core\magics\execution.py:700: UserWarning: For Windows, use double quotes to wrap a filename: %run "mypath\myfile.py"
  warn('For Windows, use double quotes to wrap a filename: %run "mypath\\myfile.py"')
ERROR:root:File `"'C:\\\\Users\\\\Daan\\\\.jupyter\\\\jupyter_console_config.py'.py"` not found.
```

Apparantly, file names need to be double quoted on Windows. I'll try and see if I can find a fix myself. Any hints on what to edit would be appriciated, as I have little experience with writing Vim plugins.

Kind regards,

Daan

**Comment by wmvanvliet** [comment]
Should be fixed now! Update to the latest version and give it a try.
