### ISSUE TITLE
jupyter-vim makes assumptions about the shell's python environment that don't play nicely with virtualenv

### ISSUE THREAD

**Issue by bzinberg** [wmvanvliet/jupyter-vim#18]
Steps to reproduce:

1. Install jupyter-vim
2. Enter a new virtualenv
3. Open a python file in vim

Result: Error within `jupyter#init_python()` because jupyter is not installed.

I think this is a UX issue -- after installing the jupyter-vim plugin, vim is unable to do things that it used to be able to do.  Namely, vim now errors on opening Python files if Jupyter is not installed within the shell's Python environment.  This is particularly noticeable if the user switches between a handful of virtualenvs, since each time they create a new one, the error in vim will show up until they install Jupyter in the new virtualenv.  I guess also as a user of vim, I would not expect changes to my Python environment to break vim.

**Comment by bzinberg** [comment]
I am leaving the issue here rather than on the main fork https://github.com/broesler/jupyter-vim because I cannot file issues on the fork.

**Comment by bzinberg** [comment]
Perhaps the simplest way to mitigate this issue is to just check whether Jupyter is installed, and if it's not, skip loading of Python, plugin keybindings, etc.

**Comment by wmvanvliet** [comment]
Does help to set the python to be used by vim explicitly, so it doesn't used the virtualenv one? 

For example, on OSX:
```
set pythonthreedll=/Library/Frameworks/Python.framework/Versions/3.6/Python
```

**Comment by bzinberg** [comment]
That is a great idea.  Based on your suggestion, I think for most virtualenv users it would be advisable to have a separate virtualenv for vim, and set paths appropriately within vimrc to use that virtualenv.  This way, Python tooling can be added or removed from vim independently of the user's (shell) Python environment.  (In particular for me, there are various reasons why I don't want to install Jupyter on my system Python.)

Was going to wait to reply until I had sample commands for how to make this work on virtualenv and Conda (then I'll send a PR adding this to the readme), but it's taking me too long to get around to it so replying now :)

**Comment by bzinberg** [comment]
It took me forever to figure out how to do this.  But I think I've got it now!

**Comment by bzinberg** [comment]
@wmvanvliet, I think https://github.com/broesler/jupyter-vim/pull/5 fixes this issue.  What's the protocol here, if any - do you merge in from there?

**Comment by wmvanvliet** [comment]
@bzinberg I've pulled from broesler's fork. Does this fix the issue?

**Comment by bzinberg** [comment]
Yeah it does, thanks.
