### ISSUE TITLE
autoscrolling

### ISSUE THREAD

**Issue by donchema** [wmvanvliet/jupyter-vim#20]
Hi,

First of all, great project! It should be noted that your branch is the only one that supports neovim. 

I have just one issue: the qtconsole window doesn't scroll at all when sending code. This is quite annoying since one has to switch to the console window and scroll down to see the output of your code.

Could this be easily fixed? I'm not that familiar with this repo, but if you can point me out to where the issue could be fixed I can start looking at it.

Many Thanks

**Comment by wmvanvliet** [comment]
This is something to fix on the qtconsole side. Could you please submit an issue to them?

**Comment by donchema** [comment]
I was just about to. I realized this was basically the qt front-end problem so I've been actually working on a fix. I'll keep you updated.

**Comment by wmvanvliet** [comment]
Closing the issue here. We can discuss on the jupyter/qtconsole repo if you have a PR to share.
